In [9]:
import pandas as pd
import numpy as np

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
data = pd.read_excel('/content/drive/MyDrive/Side effects of Drugs.xlsx')

In [11]:
df = data.head()

In [12]:
df[['drug_name' , 'side_effects']].head(15)

drug_name        side_effects
0                 Carnitine             Anaemia
1   gamma-Aminobutyric Acid      Abdominal_pain
2       Aminolevulinic Acid           Amblyopia
3                Leucovorin             Anaemia
4  5-methyltetrahydrofolate  Decreased_appetite

In [13]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [14]:
# one hot encoder
oe = OneHotEncoder(sparse=False)
ages = oe.fit_transform(data['age'].values.reshape(-1, 1))

In [15]:
age = pd.DataFrame(ages)

In [16]:
train = pd.concat([data, age], axis=1)

In [17]:
train.head()

name    age gender   race        side_effects  ...    1    2    3    4    5
0      Aaban  25-34      M  white             Anaemia  ...  1.0  0.0  0.0  0.0  0.0
1      Aabha  35-44      F  white      Abdominal_pain  ...  0.0  1.0  0.0  0.0  0.0
2      Aabid  18-24      M  white           Amblyopia  ...  0.0  0.0  0.0  0.0  0.0
3  Aabriella  35-44      F  white             Anaemia  ...  0.0  1.0  0.0  0.0  0.0
4       Aada    65+      F  white  Decreased_appetite  ...  0.0  0.0  0.0  0.0  1.0

[5 rows x 12 columns]

In [18]:
le = LabelEncoder()
train['gender'] = le.fit_transform(train['gender'])
train['race'] = le.fit_transform(train['race'])
# train['age'] = le.fit_transform(train['age'])

In [19]:
train['drug_name'] = le.fit_transform(train['drug_name'])

In [20]:
train.head()

name    age  gender  race        side_effects  ...    1    2    3    4    5
0      Aaban  25-34       1     6             Anaemia  ...  1.0  0.0  0.0  0.0  0.0
1      Aabha  35-44       0     6      Abdominal_pain  ...  0.0  1.0  0.0  0.0  0.0
2      Aabid  18-24       1     6           Amblyopia  ...  0.0  0.0  0.0  0.0  0.0
3  Aabriella  35-44       0     6             Anaemia  ...  0.0  1.0  0.0  0.0  0.0
4       Aada    65+       0     6  Decreased_appetite  ...  0.0  0.0  0.0  0.0  1.0

[5 rows x 12 columns]

In [21]:
train.isna().sum()

name            0
age             0
gender          0
race            0
side_effects    0
drug_name       0
0               0
1               0
2               0
3               0
4               0
5               0
dtype: int64

In [22]:
X = train.drop(['name', 'side_effects', 'age'], axis=1)
y = train['side_effects']

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [24]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [25]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[51  0  0 ...  0  0  0]
 [ 0 37  0 ...  0  0  0]
 [ 0  0 44 ...  0  0  0]
 ...
 [ 0  0  0 ... 35  0  0]
 [ 0  0  0 ...  0 51  0]
 [ 0  0  0 ...  0  0 19]]


0.912325